login/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'referidos.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^registrar/$', 'login.views.registrar'),
    url(r'^ingresar/$', 'login.views.ingresar'),
    url(r'^crear/usuario/$', 'login.views.crear'),
    url(r'^crear/cliente/$', 'login.views.crear_cliente'),
    url(r'^autenticar/usuario/$', 'login.views.autenticar'),
    url(r'^autenticar/cliente/$', 'login.views.autenticar_cliente'),


    url(r'^salir/$', 'login.views.salir'),
    


)

marketresellers/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'referidos.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'main.views.index'),
    url(r'^producto/$', 'main.views.producto'),

   


    


    url(r'^perfil/$', 'perfil.views.index'),


    
    url(r'^referido/(?P<usuario>[0-9]+)/(?P<tienda>[0-9]+)/', 'perfil.views.redirect_tienda'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^social/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^service/', include('registro.urls')),
    url(r'^nuevo/cliente/', 'perfil.views.nuevo_cliente'),


    #urls tienda
    url(r'^store/(?P<usuario>.+)/$', 'tienda.views.ver_tienda'),
    url(r'^tienda/crear/$', 'tienda.views.crear_tienda'),
    url(r'^tienda/visualizar/$', 'tienda.views.visualizar_tienda'),
    url(r'^tienda/productos/incluidos/$', 'tienda.views.productos_incluidos_categoria'),



     url(r'^login/', include('login.urls')),


)

perfil/models.py
from django.db import models

# Create your models here.

registro/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Tienda(models.Model):
	url = models.CharField(max_length=50,  blank = True, null = True)	
	productos =  models.ManyToManyField('Producto')
	def __unicode__(self):
		return self.url

class Venta(models.Model):
	fuente = models.CharField(max_length=50)
	valor = models.CharField(max_length=50)
	cliente = models.CharField(max_length=50)
	fecha_creacion = models.DateTimeField(auto_now_add=True)
	confirmacion_de_pago = models.BooleanField(default = False)
	vendedor =  models.ForeignKey('Perfil')

	def __unicode__(self):
		return self.fuente

class Perfil(models.Model):
	usuario = models.ForeignKey(User, null = True,  blank = True)
	tienda = models.ForeignKey('Tienda',  blank = True, null = True)
	Titular_cuenta_bancaria = models.CharField(max_length=100, blank = True, null = True)
	banco = models.CharField(max_length=50, blank = True, null = True)
	numero_cuenta = models.CharField(max_length=50, blank = True, null = True)
	pais = models.CharField(max_length=50, blank = True, null = True)
	ciudad = models.CharField(max_length=50, blank = True, null = True)

	def __unicode__(self):
		return str(self.usuario)

class Cliente(models.Model):
	usuario = models.ForeignKey(User, null = True,  blank = True)	
	pais = models.CharField(max_length=100, blank = True, null = True)
	ciudad = models.CharField(max_length=100, blank = True, null = True)
	direccion = models.CharField(max_length=100, blank = True, null = True)
	telefono = models.CharField(max_length=100, blank = True, null = True)
	fecha_creacion = models.DateTimeField(auto_now_add=True)	
	
	def __unicode__(self):
		return str(self.usuario)

class Categoria(models.Model):
	nombre = models.CharField(max_length=50, blank = True, null = True)
	

	def __unicode__(self):
		return str(self.nombre)



class Producto(models.Model):
	nombre = models.CharField(max_length=50, blank = True, null = True)
	descripcion = models.TextField(max_length=500, blank = True, null = True)
	categoria = models.ForeignKey('Categoria')
	valor = models.IntegerField(max_length=20, blank = True, null = True)
	peso = models.IntegerField(max_length=20, blank = True, null = True)
	estado = models.BooleanField(default = False)
	privado = models.BooleanField(default = False)
	def __unicode__(self):
		return str(self.nombre)


class Inventario(models.Model):
	
	
	categoria = models.ForeignKey('Producto')
	existencia = models.IntegerField(max_length=10, blank = True, null = True)	

	def __unicode__(self):
		return str(self.nombre)

perfil/views.py
from django.shortcuts import render
from django.http import HttpResponse
from registro.models import Tienda, Perfil, Cliente
# Create your views here.

def index(request):
	if request.user.is_active:
		tiendas = Tienda.objects.all()
		perfil = Perfil.objects.filter( usuario = request.user)
		if len(perfil):
			return render(request, 'perfil/index.html', {'usuario': request.user, 'tiendas': tiendas })
		else:
			perfil = Perfil()
			perfil.usuario = request.user
			perfil.save()
			return render(request, 'perfil/index.html', {'usuario': request.user, 'tiendas': tiendas })
	else:
		return render(request, 'error/index.html', { 'mensaje' : 'Por favor ingrese primero a la aplicacion.'})


def redirect_tienda(request, usuario, tienda):
	vendedora = Perfil.objects.filter( usuario__id = usuario )
	tienda = Tienda.objects.filter( id = tienda)
	#return HttpResponse(vendedora)
	return render(request, 'perfil/referido.html', {'vendedora': vendedora[0].usuario , 'tienda': tienda[0]})
	return HttpResponse("usuario: "+ usuario + " tienda: "+tienda)


def nuevo_cliente(request):

	correo = request.GET.get('correo')
	vendedora = request.GET.get('vendedora')
	tienda =  request.GET.get('tienda')
	
	#return HttpResponse("Creando cliene y redireccionando a la tienda: "+tienda)
	perfil = Perfil.objects.filter( usuario__id = vendedora)
	#return HttpResponse(perfil[0])

	cliente =  Cliente()
	cliente.tienda =  tienda
	cliente.correo = correo
	cliente.vendedor = perfil[0]
	cliente.save()
	return HttpResponse("data"+str(correo)+str(vendedora)+str(tienda))

perfil/templates/perfil/index.html
{% extends 'layouts/default.html' %}

{% block css %}
	<style type="text/css">
	.opciones{
		margin-top: 2%;
	}

	.opcion{
		
		background-color:  rgb(245, 12, 92);
		color: white;
		padding-top: 1em;
		padding-bottom: 1em;	
		
	}

	.opcion:hover{
		
		background-color:  #337ab7;
		color: white;
		
	}

	.principal{
		margin-top: 2%;
	}

	.perfil{

		
		padding-bottom: 2em;	
	}

	.mensaje-principal{
		color: rgb(245, 12, 92);
	}

	.cursor{
		cursor: pointer;
	}

	.separador{
		margin-top: 1em;
		height: 0.1em;
		width: 100%;
		background-color: rgb(245, 12, 92);
	}

	.tiendas{
		display: none;
	}

	.ventas{
		display: none;
	}

	.clientes{
		display: none;
	}
	
	</style>
{% endblock %}

{% block contenido %}
<div ng-controller="perfil">
	<input type="hidden" id="id_usuario" value="{{request.user.id}}">
	<div class="row">
		<div class="col-xs-12 col-md-2 col-lg-2 col-md-offset-1 col-lg-offset-1 color-negro  ">
			<div class="row">
				<div class="col-xs-12 col-md-12 col-lg-12 color-negro  ">
					<h3 class="opcion cursor btn-facturacion"><p class="text-center">Facturacion</p><h3>
				</div>
				<div class="col-xs-12 col-md-12 col-lg-12 color-negro  ">
					<h3 class="opcion cursor btn-tiendas" ng-click="btn_tiendas()"><p class="text-center">Tiendas</p><h3>
				</div>
				<div class="col-xs-12 col-md-12 col-lg-12 color-negro  ">
					<h3 class="opcion cursor btn-clientes" ng-click="btn_clientes()"><p class="text-center">Clientes</p><h3>
				</div>
				<div class="col-xs-12 col-md-12 col-lg-12 color-negro  ">
					<h3 class="opcion cursor btn-ventas"><p class="text-center">Ventas</p><h3>
				</div>
			</div>
		</div>

		<div class="col-xs-12 col-md-7 col-lg-7 col-md-offset-1 col-lg-offset-1 color-negro  ">
			<div class="row">
				<div class="col-xs-12 col-md-12 col-lg-12 color-negro principal perfil bg-white facturacion">
					<form>
						<h3 class="mensaje-principal">Bienvenido {{usuario.username}}, Por favor completa su informacion.</h3>
						
						<h3>Su Facturacion</h3>
					  <div class="form-group">
					    <label for="exampleInputEmail1">Nombre del Titular de la Cuenta</label>
					    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Ingrese el nombre del titular de la cuenta" ng-model="titular_cuenta">
					  </div>
					  <div class="form-group">
					    <label for="exampleInputEmail1">Su Pais</label>
					    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Ingrese Su Pais" ng-model="pais">
					  </div>
					  <div class="form-group">
					    <label for="exampleInputEmail1">Su Ciudad</label>
					    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Ingrese Su Ciudad" ng-model="ciudad">
					  </div>
					  <div class="form-group">
					    <label for="exampleInputEmail1">Nombre del Banco</label>
					    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Ingrese el Nombre del Banco" ng-model="banco">
					  </div>

					  <div class="form-group">
					    <label for="exampleInputEmail1">Su Numero de Cuenta</label>
					    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Ingrese Su Numero de Cuenta" ng-model="numero_cuenta">
					  </div>

					 
					  <button type="submit" class="btn btn-success" ng-click="modificar_perfil()">Aceptar</button>
					</form>
				</div>


				<div class="col-xs-12 col-md-12 col-lg-12 color-negro principal perfil bg-white tiendas">

					<h3 class="mensaje-principal">Bienvenido {{usuario.username}}, Por favor completa su informacion.</h3>

					<h3>Tiendas Disponibles</h3>

					<table class="table table-striped">
				      <thead>
				        <tr>
				          <th>#</th>
				          <th>Tienda</th>
				          <th>Incluir</th>
				          
				        </tr>
				      </thead>
				      <tbody>

				     
				      	<tr ng-repeat="t in tiendas">
				          <th scope="row">[[t.id]]</th>
				          <td>[[t.nombre]]</td>
				          <td><button class="btn btn-success" ng-click="incluir_tienda(t.id)" type="submit">Incluir</button></td>
				          
				          
				        </tr>
				      
				        
				      </tbody>
	   				 </table>
	   				
	   				 <div class="separador"></div>
					<h3>Sus Tiendas Incluidas</h3>

					<table class="table table-striped">
				      <thead>
				        <tr>
				          
				          <th># Tienda</th>
				         <th>Excluir</th>
				          
				        </tr>
				      </thead>
				      <tbody>

				     
				      	<tr ng-repeat="t in tiendas_incluidas">
				         
				          <th scope="row">[[t]]</th>
				          <td><button class="btn btn-danger" ng-click="excluir_tienda(t)" type="submit">Excluir</button></td>
				         
				          
				        </tr>
				      
				        
				      </tbody>
	   				 </table>
				  
				   <button type="button" class="btn btn-primary" ng-click="generar_links()">Generar Links de Referido</button>

				   <div class="separador"></div>
					<h3>Links Generados</h3>

					<table class="table table-striped">
				      <thead>
				        <tr>
				          
				          <th>Tienda</th>
				          <th>Link</th>
				         <th>Copiar</th>
				          
				        </tr>
				      </thead>
				      <tbody>

				     
				      	<tr ng-repeat="l in links">
				         
				          <th scope="row">[[l.nombre]]</th>
				          <td>[[servidor]]/referido/[[id_usuario]]/[[l.id]]</td>
				          <td><button class="btn btn-primary" ng-click="copiar_link()" >Copiar</button></td>
				        </tr>
				      
				        
				      </tbody>
	   				 </table>

				</div>

				

				<div class="col-xs-12 col-md-12 col-lg-12 color-negro principal perfil bg-white  ventas">

			
					<h3 class="mensaje-principal">Bienvenido {{usuario.username}}, Por favor completa su informacion.</h3>
					<h3>Sus Ventas</h3>
				  	<table class="table table-striped">
				      <thead>
				        <tr>
				          <th>#</th>
				          <th>Tienda</th>
				          <th>Valor</th>
				          <th>Cliente</th>
				          <th>Pago</th>
				          
				        </tr>
				      </thead>
				      <tbody>
				        <tr>
				          <th scope="row">1</th>
				          <td>yo amo los zapatos mexico</td>
				          <th>500 MX</th>
				          <th>Jhon Buendia</th>
				          <th>Pendiente</th>
				          
				        </tr>
				        <tr>
				          <th scope="row">2</th>
				          <td>yo amo los zapatos colombia</td>
				          <th>500 MX</th>
				          <th>Jhon Buendia</th>
				          <th>Pendiente</th>
				          
				        </tr>
				        
				      </tbody>
	   				 </table>
				   


				</div>
			</div>

			<div class="col-xs-12 col-md-12 col-lg-12 color-negro principal perfil bg-white clientes">

			
					<h3 class="mensaje-principal">Bienvenido {{usuario.username}}.</h3>
					<h3>Sus Clintes</h3>
				  	<table class="table table-striped">
				      <thead>
				        <tr>
				          <th>#</th>
				          <th>Correo</th>
				          <th>Tienda</th>
				          <th>Fecha</th>
				          
				          
				        </tr>
				      </thead>
				      <tbody>
				        <tr ng-repeat="c in clientes">
				          <th scope="row">[[$index]]</th>
				          <td>[[c.correo]]</td>
				          <td>[[c.tienda]]</td>
				          <td>[[c.fecha_creacion | date :  yyyy-MM-ddTHH:mm  ]]</td>
				          
				        </tr>
				        
				        
				      </tbody>
	   				 </table>
				   


				</div>





		</div>

	</div>

	
{% endblock %}

{% block scripts %}
<script type="text/javascript">
	$( document ).ready(function() {
    $('.btn-facturacion').click(function(){
    	$('.facturacion').css('display', 'block');
    	$('.tiendas').css('display', 'none');
    	$('.ventas').css('display', 'none');
    	$('.clientes').css('display', 'none')
    });
    $('.btn-tiendas').click(function(){
    	$('.facturacion').css('display', 'none');
    	$('.tiendas').css('display', 'block');
    	$('.ventas').css('display', 'none');
    	$('.clientes').css('display', 'none')

    });
    $('.btn-ventas').click(function(){
    	$('.facturacion').css('display', 'none');
    	$('.tiendas').css('display', 'none');
    	$('.ventas').css('display', 'block');
    	$('.clientes').css('display', 'none')
    });

    $('.btn-clientes').click(function(){
    	
    });
});	

</script>

    {% endblock %}

perfil/templates/perfil/index_old.html
{% extends 'layouts/default.html' %}

{% block css %}
	<style type="text/css">
	.opciones{
		margin-top: 2%;
	}

	.opcion{
		
		background-color: white;
		padding-top: 1em;
		padding-bottom: 1em;	
		
	}

	.opcion:hover{
		
		background-color:  rgb(245, 12, 92);
		color: white;
		
	}

	.principal{
		margin-top: 2%;
	}

	.perfil{

		border-radius: 5px;
		padding-bottom: 2em;	
	}

	.mensaje-principal{
		color: rgb(245, 12, 92);
	}

	.cursor{
		cursor: pointer;
	}

	.tiendas{
		display: none;
	}

	.ventas{
		display: none;
	}
	
	</style>
{% endblock %}

{% block contenido %}
<div ng-controller="perfil">
	<div class="row opciones">
		<div class="col-xs-12 col-md-2 col-lg-2 col-md-offset-3 col-lg-offset-3 color-negro  ">
			<h3 class="opcion cursor btn-facturacion"><p class="text-center">Facturacion</p><h3>
		</div>
		<div class="col-xs-12 col-md-2 col-lg-2   ">
			<h3 class="opcion cursor btn-tiendas"><p class="text-center">Tiendas</p><h3>			
		</div>
		<div class="col-xs-12 col-md-2 col-lg-2 ">
			<h3 class="opcion cursor btn-ventas"><p class="text-center">Ventas</p><h3>
			
		</div>
	</div>
	
	<div class="row principal">
	  	<div class="col-xs-12 col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2 color-negro perfil bg-white facturacion">

			<form>
				<h3 class="mensaje-principal">Bienvenido {{usuario.username}}, Por favor completa su informacion.</h3>
				
				<h3>Su Facturacion</h3>
			  <div class="form-group">
			    <label for="exampleInputEmail1">Nombre del Titular de la Cuenta</label>
			    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Ingrese el nombre del titular de la cuenta">
			  </div>
			  <div class="form-group">
			    <label for="exampleInputEmail1">Nombre del Banco</label>
			    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Ingrese el Nombre del Banco">
			  </div>

			  <div class="form-group">
			    <label for="exampleInputEmail1">Su Numero de Cuenta</label>
			    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Ingrese Su Numero de Cuenta">
			  </div>

			 
			  <button type="submit" class="btn btn-success">Aceptar</button>
			</form>
	  		
	  	</div>



	  	<div class="col-xs-12 col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2 color-negro perfil bg-white tiendas"

			<form>
				<h3 class="mensaje-principal">Bienvenido {{usuario.username}}, Por favor completa su informacion.</h3>
				<h3>Sus Tiendas Referidas</h3>

				<table class="table table-striped">
			      <thead>
			        <tr>
			          <th>#</th>
			          <th>Tienda</th>
			          <th>Incluir</th>
			          
			        </tr>
			      </thead>
			      <tbody>

			     
			      	<tr ng-repeat="t in tiendas">
			          <th scope="row">[[$index]]</th>
			          <td>[[t.nombre]]</td>
			          <td> <input type="checkbox" ng-click="incluir_tienda(t.id)"></td>
			          
			        </tr>
			      
			        
			      </tbody>
   				 </table>
			   <button type="submit" class="btn btn-success">Aceptar</button>
			   <button type="button" class="btn btn-primary">Generar Links de Referido</button>
	  		
	  	</div>


	  	<div class="col-xs-12 col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2 color-negro perfil bg-white ventas">

			<form>
				<h3 class="mensaje-principal">Bienvenido {{usuario.username}}, Por favor completa su informacion.</h3>
				<h3>Sus Ventas</h3>
			  	<table class="table table-striped">
			      <thead>
			        <tr>
			          <th>#</th>
			          <th>Tienda</th>
			          <th>Valor</th>
			          <th>Cliente</th>
			          <th>Pago</th>
			          
			        </tr>
			      </thead>
			      <tbody>
			        <tr>
			          <th scope="row">1</th>
			          <td>yo amo los zapatos mexico</td>
			          <th>500 MX</th>
			          <th>Jhon Buendia</th>
			          <th>Pendiente</th>
			          
			        </tr>
			        <tr>
			          <th scope="row">2</th>
			          <td>yo amo los zapatos colombia</td>
			          <th>500 MX</th>
			          <th>Jhon Buendia</th>
			          <th>Pendiente</th>
			          
			        </tr>
			        
			      </tbody>
   				 </table>
			   <button type="submit" class="btn btn-success">Aceptar</button>
			   <button type="button" class="btn btn-primary">Generar Informe de Ventas</button>
	  		
	  	</div>
	  
  	</div>
</div> 
{% endblock %}

{% block scripts %}
<script type="text/javascript">
	$( document ).ready(function() {
    $('.btn-facturacion').click(function(){
    	$('.facturacion').css('display', 'block');
    	$('.tiendas').css('display', 'none');
    	$('.ventas').css('display', 'none');
    });
    $('.btn-tiendas').click(function(){
    	$('.facturacion').css('display', 'none');
    	$('.tiendas').css('display', 'block');
    	$('.ventas').css('display', 'none');

    });
    $('.btn-ventas').click(function(){
    	$('.facturacion').css('display', 'none');
    	$('.tiendas').css('display', 'none');
    	$('.ventas').css('display', 'block');
    });
});	

</script>

    {% endblock %}

perfil/templates/perfil/referido.html
{% extends 'layouts/default.html' %}

{% block css %}
<style type="text/css">
	.contenido{
		margin-top: 5em;
		background-color: white;
		padding-bottom: 3em;
		
	}

	.vendedora{
		color:rgb(245, 12, 92);
	}
</style>
{% endblock %}

{% block contenido %}
	<div ng-controller="perfil">
		<input type="hidden" id="vendedora" value="{{vendedora.id}}">
		<input type="hidden" id="tienda" value="{{tienda.url}}">
		<div class="row">
			<div class="col-xs-12 col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2 contenido">
			<p><h3>Bienvenida a {{tienda.nombre}}, has llegado a nosotros gracias a {{vendedora.username}}, por favor dejanos tu email para continual y disfrutar de todos nuestros productos.</h3></p>
				<div class="form-inline">
  
				  <div class="form-group">
				    
				    <input  type="email" class="form-control" id="correo" placeholder="jane.doe@example.com" size="40" >
				  </div>
				  <button type="submit" class="btn btn-primary" ng-click="go_tienda()">Continuar</button>
				</div>
			</div>
		</div>
	</div>
{% endblock %}